version: 2
jobs:
  build:
    docker:
      - image: cimg/node:15.5.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm i
      - run: npm run build

  deploy:
    docker:
      - image: cimg/node:15.5.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "64:67:55:e8:04:c6:63:d2:aa:d3:c7:e8:cf:17:6d:0f"
      - run: npm i
      - run: npm run build
      - run: git config user.email "wkgreen13@gmail.com"
      - run: git config user.name "CircleCI"
      - run: git stash
      - run: echo $(npm version patch) >> $VERSION
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: npm publish
      - run: git push origin v$VERSION

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master
