name: NPM Publish
on: [pull_request]
jobs:
  Publish:
    runs-on: macos-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Checkout
        uses: actions/checkout@v2
      - run: cd ${{github.workspace}}
      - name: NPM Install
        run: npm i
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish
        env: 
          NODE_AUTH_TOKEN: ${{NPM_TOKEN}}
