name: Tag Release
on: [push]
jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Checkout
        uses: actions/checkout@v2
      - run: cd ${{github.workspace}}
      - name: Tag
        run: npm run tag
      - name: List Tags
        run: git tag
